### ISSUE TITLE
Nordic countries

### ISSUE THREAD

**Issue by vladdeSV** [vladdeSV/php-nin#1]
For a first release I would like to support the Nordic countries. This is a summary of what is and is not implemented*.

* = based on my knowledge right now. More will be added if discovered.

### Sweden
- [x] Ordinary personal identification numbers
- [x] Co-ordination number
- [ ] ~Organization number~

### Norway
- [x] Ordinary birth numbers
- [x] D-numbers
- [x] H-numbers
- [ ] ~FH-numbers~

### Finland
- [x] Ordinary personal identity codes

### Denmark
- [x] Ordinary personal identification numbers

### Iceland
- [x] Ordinary identification numbers

**Comment by vladdeSV** [comment]
I am leaving out Norwegian FH-numbers and Swedish Organization numbers, as I do not believe they currently should be handled.
